refactor(git): Apply various small changes to git-credential-bitwarden

diff --git a/.local/bin/git-credential-bitwarden b/.local/bin/git-credential-bitwarden
--- a/.local/bin/git-credential-bitwarden
+++ b/.local/bin/git-credential-bitwarden
@@ -74,14 +74,12 @@ credential_get() {
     return 1
   fi
 
-  # Get configuration overrides.
-  local baseurl="$protocol://$host"
-
   # Retrieve the item.
   local bw_item
   if [ -z "${args[item-id]}" ]; then
     # No item id provided. Search for the URL.
-    bw_item="$(bw get item "$baseurl" 2>/dev/null)"
+    local baseurl="$protocol://$host"
+    bw_item="$(bw get item "$baseurl")"
     local err=$?
     if [ $err -ne 0 ] || [ -z "$bw_item" ]; then
       if [ "${args[force]}" = true ]; then
@@ -97,10 +95,10 @@ credential_get() {
     fi
   else
     # Retrieve the specified item.
-    bw_item="$(bw get item "${args[item-id]}" 2>/dev/null)"
+    bw_item="$(bw get item "${args[item-id]}")"
     local err=$?
     if [ $err -ne 0 ] || [ -z "$bw_item" ]; then
-      >&2 echo "\e[31mItem '${args[item-id]}' was not found in Bitwarden vault.\e[m"
+      >&2 echo "\e[31mUnable to retrieve item '${args[item-id]}' from Bitwarden vault.\e[m"
       echo 'quit=true'
       return 1
     fi
